### ISSUE TITLE
Unicorn controlled content does not create links in linkdatabase

### ISSUE THREAD

**Issue by UffeHammer** [SitecoreUnicorn/Unicorn#363]
Hello

We have a problem where Unicorn controlled content does not create links in linkdatabase, so items that have links to datasource items in a child folder called Datasources never gets the links created in the link database. All of the items are Unicorn controlled in the same "Predicate Component" so maybe that could be a clue to the problem?

We are running version 4.1.1 Transparent sync disabled

Cheers
uffe

**Comment by cassidydotdk** [comment]
No, having it all in the same Predicate is what I often do.

What IS a problem however, is how you configured this setting:

https://github.com/SitecoreUnicorn/Unicorn/blob/master/src/Unicorn/Standard%20Config%20Files/Unicorn.Configs.Default.example#L121

					<syncConfiguration updateLinkDatabase="false" updateSearchIndex="false" />

The defaults that ship with Unicorn will ignore the LinkDatabase. Switch this setting to `true` and you should see it begin to pick up :-)

**Comment by UffeHammer** [comment]
Thats a reasonable explanation, but why on earth would you want to disable updating the linkdatabase?
I get it that the index could be slow, but surely the linkdatabase isn't that slow?

**Comment by cassidydotdk** [comment]
It's one of those cases where a choice has to be made, and I don't think @kamsar and I are in 100% agreement on this particular one ;-)

Enabling either of these settings would mean, that a job has to run which would otherwise be seamless - where for instance Transparent Sync is in play.

I guess it comes down to, HOW many people use and care about the LinkDatabase in their day to day. Me, personally, I always flip this switch to `true`. But if I am to judge by the number of times someone has come to me and asked about this, I doubt it matters to very many people. And as such, having it off by default makes sense.
