### ISSUE TITLE
Transparent Sync Errors Flooding Logs Bug

### ISSUE THREAD

**Issue by jesslich423** [SitecoreUnicorn/Unicorn#396]
**POTENTIAL BUG**

The Sitecore logs are being flooded with the error about fast queries being performed on one or more configurations using Transparent Sync. The item that it's complaining about, the Dictionary Domain ({0A2847E6-9885-450B-B61E-F9E6528480EF}), isn't included in any Unicorn configuration. This is just a standard Sitecore item that comes by default. What's even weirder is that I removed the fast query, published, and my logs are still being flooded with the same error. 

```
22716 14:30:27 WARN  [Unicorn] A Fast Query was performed and Unicorn had one or more configurations enabled that used Transparent Sync. Fast Query is not supported with Transparent Sync. Either stop using Fast Query (it's generally regarded as a bad idea in almost every circumstance), or disable Transparent Sync for all configurations.
22716 14:30:27 WARN  [Unicorn] The Fast Query was: //*[@@templateid='{0A2847E6-9885-450B-B61E-F9E6528480EF}' and @@key!='__standard values']
22716 14:30:27 WARN  [Unicorn] The call stack that made the Fast Query was:    at Unicorn.Data.DataProvider.UnicornSqlServerDataProvider.QueryFast(String query, CallContext context)
```

This is occurring on Sitecore 9.2 using Unicorn 4.1.1.

**Comment by cassidydotdk** [comment]
fast: query bypasses data providers and goes directly to SQL; hence it will lead to unpredictable results if you try and use it with Transparent Sync (which relies on the Unicorn Data Provider).

Either rid yourself of all fast: querying, or disable Transparent Sync. You cannot have both.

The exception message literally tells you this.

```
Either stop using Fast Query (it's generally regarded as a bad idea in almost every circumstance), or disable Transparent Sync for all configurations.
```

On a side note; `//*[@@templateid='{0A2847E6-9885-450B-B61E-F9E6528480EF}' and @@key!='__standard values']` is a _ghastly_ query call that will absolutely KILL your performance if you put this live. You should definitely refactor this out.

https://intothecloud.blog/2018/10/21/It-s-time-to-put-fast-query-to-rest/

**Comment by jesslich423** [comment]
I understand the error, but this isn't an item included in any of my configurations, so I don't understand why I am getting it. Shouldn't I only receive that error if I have an item that is using a fast query included in one of my configs that has transparent sync enabled? The fast query is originating from an item that is installed with Sitecore, this is not something we've implemented.

**Comment by cassidydotdk** [comment]
Well you're getting it because _somewhere_ in either your code or other code you have running (SXA maybe?), a call for `//*[@@templateid='{0A2847E6-9885-450B-B61E-F9E6528480EF}' and @@key!='__standard values']` is executed. `//*` will literally traverse the _entire_ item tree, which will obviously also hit items that are under Unicorn control. `//*` is why I react the way I do, it will effectively do a `SELECT * ON [Items]` - your entire database. It will _shred_ your SQL Server.

I can't guess from where in the code base this happens. I suggest you start by looking up template `{0A2847E6-9885-450B-B61E-F9E6528480EF}` and see if it matches up with anything in your solution. It should provide some sort of clue.
