### ISSUE TITLE
Standard Values Item That Was Deleted Keeps Being Re-Created

### ISSUE THREAD

**Issue by jesslich423** [SitecoreUnicorn/Unicorn#397]
We have created two Template items that inherit from Standard Rendering Parameters. When these templates were created, no standard values item was created with them. If we open a page in Experience Editor that has a component that uses one of these rendering parameters template, a standard values item is created on the template. The only errors visible in the logs are due to another bug ticket I have opened with you (Transparent Sync Errors Flooding Logs Bug #396). I tried opening a ticket with Sitecore Support, but they concluded it's an issue with Unicorn.

**Comment by cassidydotdk** [comment]
Rendering Parameters are about the only types of `Item` in Sitecore that never can or should have `Standard Values` since they are never created as a real `Sitecore.Data.Item`.

I assure you however, Unicorn does not create Standard Values items under any other circumstance than if you have it in a YAML file on disk and you're telling it to sync.

Disable t-sync alternatively disable Unicorn entirely to confirm this.

**Comment by jesslich423** [comment]
Solid advice, thanks for that! Didn't think to just disable Unicorn entirely. After doing so, the issue is still happening, so definitely appears like it is a Sitecore issue after all. Thank you again!
